spring:
  application:
    name: gateway-zuul-demo
server:
  port: 8040

zuul:
  routes:
    user:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /test/**                                    # 想要映射到的路径
      url: http://localhost:8080/test