spring:
  application:
    name: gateway-zuul-demo
server:
  port: 8040

zuul:
  routes:
    user:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /testapp/**                                    # 想要映射到的路径
      service_id: test-app


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/