spring:
  application:
    name: eureka-server-demo


server:
  port: 9002


eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    defaultZone: http://127.0.0.1:9001/eureka/


