spring:
  application:
    name: eureka-server-demo


server:
  port: 9001


eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
#    defaultZone: http://127.0.0.1:9002/eureka/


